# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Java User Group Guadalajara
email: admin@juggdl.org
description: >- # this means to ignore newlines until "baseurl:"
  En Java User Group Guadalajara tendrás oportunidad de conocer developers Java y hablar acerca de código, patrones, innovaciones y compartir tus ideas.
  Nuestras reuniones son técnicas e incluyen a expertos en la tecnología Java. Damos la bienvenida a todas las personas sin importar su background o expertis tecnico.
  No te pierdas nuestras reuniones y siguenos en nuestras redes sociales.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://juggdl.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: java_gdl
github_username:  gdljug

# Build settings
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one
github: [metadata]
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
